### ISSUE TITLE
Add support PHP

### ISSUE THREAD

**Issue by williamokano** [thecodershub/algorithms#57]
Please add support for PHP :)

**Comment by thecodershub** [comment]
We have a lot of languages right now, spanning across multiple paradigms. We might add PHP later, but not right now. You can try other languages for now :)

**Comment by williamokano** [comment]
:( so sad :(

**Comment by thecodershub** [comment]
Well, we'll add it. Maybe more people will come forward and contribute then. Please do read the contributing guidelines beforehand and add PHP to the README.
